// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/go-loom/examples/plugins/evmexample/types/types.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/go-loom/examples/plugins/evmexample/types/types.proto

It has these top-level messages:
	EthTransaction
	EthCall
	EthCallResult
*/
package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EthTransaction struct {
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *EthTransaction) Reset()                    { *m = EthTransaction{} }
func (m *EthTransaction) String() string            { return proto.CompactTextString(m) }
func (*EthTransaction) ProtoMessage()               {}
func (*EthTransaction) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

func (m *EthTransaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EthTransaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EthCall struct {
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *EthCall) Reset()                    { *m = EthCall{} }
func (m *EthCall) String() string            { return proto.CompactTextString(m) }
func (*EthCall) ProtoMessage()               {}
func (*EthCall) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

func (m *EthCall) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EthCall) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EthCallResult struct {
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *EthCallResult) Reset()                    { *m = EthCallResult{} }
func (m *EthCallResult) String() string            { return proto.CompactTextString(m) }
func (*EthCallResult) ProtoMessage()               {}
func (*EthCallResult) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{2} }

func (m *EthCallResult) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EthCallResult) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*EthTransaction)(nil), "EthTransaction")
	proto.RegisterType((*EthCall)(nil), "EthCall")
	proto.RegisterType((*EthCallResult)(nil), "EthCallResult")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/go-loom/examples/plugins/evmexample/types/types.proto", fileDescriptorTypes)
}

var fileDescriptorTypes = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8e, 0xb1, 0x0e, 0x82, 0x30,
	0x14, 0x45, 0x83, 0x31, 0x92, 0x34, 0xe2, 0xc0, 0xc4, 0x48, 0x98, 0x58, 0xa4, 0x83, 0x83, 0x93,
	0x2e, 0x86, 0xcd, 0x89, 0xf8, 0x03, 0x05, 0x5f, 0xa0, 0xb1, 0xed, 0x6b, 0xda, 0x57, 0xd4, 0xbf,
	0x37, 0x22, 0x7e, 0x00, 0xcb, 0xcd, 0x3d, 0x37, 0x39, 0xc9, 0x65, 0xd7, 0x5e, 0xd2, 0x10, 0xda,
	0xaa, 0x43, 0xcd, 0x15, 0xa2, 0x36, 0x40, 0x4f, 0x74, 0x0f, 0xde, 0xe3, 0xfe, 0x8b, 0x1c, 0x5e,
	0x42, 0x5b, 0x05, 0x9e, 0x5b, 0x15, 0x7a, 0x69, 0x3c, 0x87, 0x51, 0xcf, 0x1b, 0xa7, 0xb7, 0x05,
	0xff, 0xcb, 0xca, 0x3a, 0x24, 0x2c, 0xce, 0x6c, 0x57, 0xd3, 0x70, 0x73, 0xc2, 0x78, 0xd1, 0x91,
	0x44, 0x93, 0x66, 0x2c, 0x1e, 0xc1, 0x79, 0x89, 0x26, 0x8b, 0xf2, 0xa8, 0x4c, 0x9a, 0x3f, 0xa6,
	0x29, 0x5b, 0xdf, 0x05, 0x89, 0x6c, 0x95, 0x47, 0xe5, 0xb6, 0x99, 0x7a, 0x71, 0x64, 0x71, 0x4d,
	0xc3, 0x45, 0x28, 0xb5, 0x50, 0x3c, 0xb1, 0x64, 0x16, 0x1b, 0xf0, 0x41, 0xd1, 0x32, 0xbd, 0xdd,
	0x4c, 0xf7, 0x0f, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x86, 0x52, 0xa5, 0x0e, 0x01, 0x00,
	0x00,
}
